services:
  postgres:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=quarkus_test
      - POSTGRES_PASSWORD=quarkus_test
    ports:
      - "15432:15432"

volumes:
  postgres: